-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [bit_block_ops]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace bit_block_ops

/-- [core::hash::Hasher::write_u32]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 374:4-374:35
    Name pattern: [core::hash::Hasher::write_u32]
    Visibility: public -/
@[trait_default, rust_fun "core::hash::Hasher::write_u32"]
axiom core.hash.Hasher.write_u32.default
  {Self : Type} (HasherInst : core.hash.Hasher Self) :
  Self → Std.U32 → Result Self

/-- [bit_block_ops::count_ones]:
    Source: 'tests/src/bit_block_ops.rs', lines 7:0-9:1
    Visibility: public -/
def count_ones (x : Std.U32) : Result Std.U32 := do
  core.num.U32.countOnes x

/-- [bit_block_ops::hash]:
    Source: 'tests/src/bit_block_ops.rs', lines 11:0-13:1
    Visibility: public -/
def hash
  {H : Type} (corehashHasherInst : core.hash.Hasher H) (x : Std.U32)
  (state : H) :
  Result H
  := do
  core.hash.hashU32 corehashHasherInst x state

/-- [bit_block_ops::OverrideHasher]
    Source: 'tests/src/bit_block_ops.rs', lines 15:0-18:1
    Visibility: public -/
structure OverrideHasher where
  seen : Std.U32
  calls : Std.U32

/-- [bit_block_ops::{impl core::hash::Hasher for bit_block_ops::OverrideHasher}::write_u32]:
    Source: 'tests/src/bit_block_ops.rs', lines 28:4-31:5
    Visibility: public -/
def OverrideHasher.Insts.CoreHashHasher.write_u32
  (self : OverrideHasher) (value : Std.U32) : Result OverrideHasher := do
  let i ← self.calls + 1#u32
  ok { seen := value, calls := i }

/-- [bit_block_ops::{impl core::hash::Hasher for bit_block_ops::OverrideHasher}::write]:
    Source: 'tests/src/bit_block_ops.rs', lines 24:4-27:5
    Visibility: public -/
def OverrideHasher.Insts.CoreHashHasher.write
  (self : OverrideHasher) (_bytes : Slice Std.U8) : Result OverrideHasher := do
  let i ← self.calls + 100#u32
  ok { seen := 0#u32, calls := i }

/-- [bit_block_ops::{impl core::hash::Hasher for bit_block_ops::OverrideHasher}::finish]:
    Source: 'tests/src/bit_block_ops.rs', lines 21:4-23:5
    Visibility: public -/
def OverrideHasher.Insts.CoreHashHasher.finish
  (self : OverrideHasher) : Result Std.U64 := do
  ok (UScalar.cast .U64 self.seen)

/-- Trait implementation: [bit_block_ops::{impl core::hash::Hasher for bit_block_ops::OverrideHasher}]
    Source: 'tests/src/bit_block_ops.rs', lines 20:0-32:1 -/
@[reducible]
def OverrideHasher.Insts.CoreHashHasher : core.hash.Hasher OverrideHasher := {
  finish := OverrideHasher.Insts.CoreHashHasher.finish
  write := OverrideHasher.Insts.CoreHashHasher.write
  write_u32 := OverrideHasher.Insts.CoreHashHasher.write_u32
}

/-- [bit_block_ops::check_count]:
    Source: 'tests/src/bit_block_ops.rs', lines 35:0-41:1
    Visibility: public -/
def check_count : Result Unit := do
  let i ← count_ones 0#u32
  massert (i = 0#u32)
  let i1 ← count_ones 4294967295#u32
  massert (i1 = 32#u32)
  let i2 ← count_ones 2147483649#u32
  massert (i2 = 2#u32)
  let i3 ← count_ones 2863311530#u32
  massert (i3 = 16#u32)
  let i4 ← count_ones 1#u32
  massert (i4 = 1#u32)

/- Unit test for [bit_block_ops::check_count] -/
#assert (check_count).reducesTo ()

/-- [bit_block_ops::check_hash_dispatch]:
    Source: 'tests/src/bit_block_ops.rs', lines 44:0-52:1
    Visibility: public -/
def check_hash_dispatch : Result Unit := do
  let h ←
    hash OverrideHasher.Insts.CoreHashHasher 305419896#u32
      { seen := 0#u32, calls := 0#u32 }
  massert (h.seen = 305419896#u32)
  massert (h.calls = 1#u32)
  let h1 ← hash OverrideHasher.Insts.CoreHashHasher 0#u32 h
  massert (h1.seen = 0#u32)
  massert (h1.calls = 2#u32)

/- Unit test for [bit_block_ops::check_hash_dispatch] -/
#assert (check_hash_dispatch).reducesTo ()

end bit_block_ops
