-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [floats]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace floats

/-- [floats::eq32]:
    Source: 'tests/src/floats.rs', lines 6:0-8:1
    Visibility: public -/
def eq32 (x : F32) (y : F32) : Result Bool := do
  ok (F32.eq x y)

/-- [floats::ne32]:
    Source: 'tests/src/floats.rs', lines 9:0-11:1
    Visibility: public -/
def ne32 (x : F32) (y : F32) : Result Bool := do
  ok (F32.ne x y)

/-- [floats::lt32]:
    Source: 'tests/src/floats.rs', lines 12:0-14:1
    Visibility: public -/
def lt32 (x : F32) (y : F32) : Result Bool := do
  ok (F32.lt x y)

/-- [floats::le32]:
    Source: 'tests/src/floats.rs', lines 15:0-17:1
    Visibility: public -/
def le32 (x : F32) (y : F32) : Result Bool := do
  ok (F32.le x y)

/-- [floats::gt32]:
    Source: 'tests/src/floats.rs', lines 18:0-20:1
    Visibility: public -/
def gt32 (x : F32) (y : F32) : Result Bool := do
  ok (F32.gt x y)

/-- [floats::ge32]:
    Source: 'tests/src/floats.rs', lines 21:0-23:1
    Visibility: public -/
def ge32 (x : F32) (y : F32) : Result Bool := do
  ok (F32.ge x y)

/-- [floats::neg32]:
    Source: 'tests/src/floats.rs', lines 24:0-26:1
    Visibility: public -/
def neg32 (x : F32) : Result F32 := do
  ok (F32.neg x)

/-- [floats::eq64]:
    Source: 'tests/src/floats.rs', lines 27:0-29:1
    Visibility: public -/
def eq64 (x : F64) (y : F64) : Result Bool := do
  ok (F64.eq x y)

/-- [floats::ne64]:
    Source: 'tests/src/floats.rs', lines 30:0-32:1
    Visibility: public -/
def ne64 (x : F64) (y : F64) : Result Bool := do
  ok (F64.ne x y)

/-- [floats::lt64]:
    Source: 'tests/src/floats.rs', lines 33:0-35:1
    Visibility: public -/
def lt64 (x : F64) (y : F64) : Result Bool := do
  ok (F64.lt x y)

/-- [floats::le64]:
    Source: 'tests/src/floats.rs', lines 36:0-38:1
    Visibility: public -/
def le64 (x : F64) (y : F64) : Result Bool := do
  ok (F64.le x y)

/-- [floats::gt64]:
    Source: 'tests/src/floats.rs', lines 39:0-41:1
    Visibility: public -/
def gt64 (x : F64) (y : F64) : Result Bool := do
  ok (F64.gt x y)

/-- [floats::ge64]:
    Source: 'tests/src/floats.rs', lines 42:0-44:1
    Visibility: public -/
def ge64 (x : F64) (y : F64) : Result Bool := do
  ok (F64.ge x y)

/-- [floats::neg64]:
    Source: 'tests/src/floats.rs', lines 45:0-47:1
    Visibility: public -/
def neg64 (x : F64) : Result F64 := do
  ok (F64.neg x)

/-- [floats::constants32]:
    Source: 'tests/src/floats.rs', lines 49:0-51:1
    Visibility: public -/
def constants32 : Result (F32 × F32 × F32 × F32 × F32 × F32) := do
  ok (F32.ofBits 0, F32.ofBits 2147483648, F32.ofBits 1036831949,
    F32.ofBits 8388608, F32.ofBits 2139095039, F32.ofBits 1)

/-- [floats::constants64]:
    Source: 'tests/src/floats.rs', lines 52:0-61:1
    Visibility: public -/
def constants64 : Result (F64 × F64 × F64 × F64 × F64 × F64) := do
  ok (F64.ofBits 0, F64.ofBits 9223372036854775808,
    F64.ofBits 4591870180066957722, F64.ofBits 4503599627370496,
    F64.ofBits 9218868437227405311, F64.ofBits 1)

/-- [floats::comparisons]:
    Source: 'tests/src/floats.rs', lines 64:0-80:1
    Visibility: public -/
def comparisons : Result Unit := do
  let b ← eq32 (F32.ofBits 0) (F32.ofBits 2147483648)
  massert b
  let b1 ← eq64 (F64.ofBits 0) (F64.ofBits 9223372036854775808)
  massert b1
  let b2 ← lt32 (F32.ofBits 0) (F32.ofBits 2147483648)
  massert (¬ b2)
  let b3 ← lt32 (F32.ofBits 3221225472) (F32.ofBits 3212836864)
  massert b3
  let b4 ← le32 (F32.ofBits 3212836864) (F32.ofBits 0)
  massert b4
  let b5 ← gt32 (F32.ofBits 1073741824) (F32.ofBits 1065353216)
  massert b5
  let b6 ← ge32 (F32.ofBits 1065353216) (F32.ofBits 1065353216)
  massert b6
  let b7 ← ne32 (F32.ofBits 1065353216) (F32.ofBits 1073741824)
  massert b7
  let b8 ←
    lt64 (F64.ofBits 13835058055282163712) (F64.ofBits 13830554455654793216)
  massert b8
  let b9 ← le64 (F64.ofBits 13830554455654793216) (F64.ofBits 0)
  massert b9
  let b10 ←
    gt64 (F64.ofBits 4611686018427387904) (F64.ofBits 4607182418800017408)
  massert b10
  let b11 ←
    ge64 (F64.ofBits 4607182418800017408) (F64.ofBits 4607182418800017408)
  massert b11
  let b12 ←
    ne64 (F64.ofBits 4607182418800017408) (F64.ofBits 4611686018427387904)
  massert b12
  let fl ← neg32 (F32.ofBits 1065353216)
  let b13 ← eq32 fl (F32.ofBits 3212836864)
  massert b13
  let fl1 ← neg64 (F64.ofBits 4607182418800017408)
  let b14 ← eq64 fl1 (F64.ofBits 13830554455654793216)
  massert b14

/- Unit test for [floats::comparisons] -/
#assert (comparisons).reducesTo ()

/-- [floats::infinities32]:
    Source: 'tests/src/floats.rs', lines 84:0-86:1
    Visibility: public -/
def infinities32 : Result (F32 × F32) := do
  ok (F32.ofBits 2139095040, F32.ofBits 4286578688)

/-- [floats::infinities64]:
    Source: 'tests/src/floats.rs', lines 88:0-90:1
    Visibility: public -/
def infinities64 : Result (F64 × F64) := do
  ok (F64.ofBits 9218868437227405312, F64.ofBits 18442240474082181120)

end floats
