-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [floats_std]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace floats_std

/-- [floats_std::clone32]:
    Source: 'tests/src/floats_std.rs', lines 5:0-7:1
    Visibility: public -/
def clone32 (x : F32) : Result F32 := do
  F32.clone x

/-- [floats_std::default32]:
    Source: 'tests/src/floats_std.rs', lines 8:0-10:1
    Visibility: public -/
def default32 : Result F32 := do
  F32.default

/-- [floats_std::partial_cmp32]:
    Source: 'tests/src/floats_std.rs', lines 11:0-13:1
    Visibility: public -/
def partial_cmp32 (x : F32) (y : F32) : Result (Option Ordering) := do
  F32.partial_cmp x y

/-- [floats_std::infinity32]:
    Source: 'tests/src/floats_std.rs', lines 14:0-16:1
    Visibility: public -/
def infinity32 : Result F32 := do
  ok F32.INFINITY

/-- [floats_std::clone64]:
    Source: 'tests/src/floats_std.rs', lines 18:0-20:1
    Visibility: public -/
def clone64 (x : F64) : Result F64 := do
  F64.clone x

/-- [floats_std::default64]:
    Source: 'tests/src/floats_std.rs', lines 21:0-23:1
    Visibility: public -/
def default64 : Result F64 := do
  F64.default

/-- [floats_std::partial_cmp64]:
    Source: 'tests/src/floats_std.rs', lines 24:0-26:1
    Visibility: public -/
def partial_cmp64 (x : F64) (y : F64) : Result (Option Ordering) := do
  F64.partial_cmp x y

/-- [floats_std::infinity64]:
    Source: 'tests/src/floats_std.rs', lines 27:0-29:1
    Visibility: public -/
def infinity64 : Result F64 := do
  ok F64.INFINITY

end floats_std
