-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [function_item_lifetimes]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace function_item_lifetimes

/-- [function_item_lifetimes::apply]:
    Source: 'tests/src/function_item_lifetimes.rs', lines 5:0-7:1 -/
def apply
  {F : Type} (coreopsfunctionFnMutFTupleShared0U8U8Inst :
  core.ops.function.FnMut F Std.U8 Std.U8) (f : F) (x : Std.U8) :
  Result Std.U8
  := do
  let (i, _) ← coreopsfunctionFnMutFTupleShared0U8U8Inst.call_mut f x
  ok i

/-- [function_item_lifetimes::checked]:
    Source: 'tests/src/function_item_lifetimes.rs', lines 8:0-10:1 -/
def checked (x : Std.U8) : Result Std.U8 := do
  x + 1#u8

/-- [function_item_lifetimes::{impl core::ops::function::FnMut<(&'_0 u8,), u8> for for<'_0_1> function_item_lifetimes::checked<'_0_1>}::call_mut]:
    Source: 'tests/src/function_item_lifetimes.rs', lines 8:0-10:1 -/
def P.Insts.CoreOpsFunctionFnMutTupleShared0U8U8.call_mut
  (state : Std.U8 → Result Std.U8) (args : Std.U8) :
  Result (Std.U8 × (Std.U8 → Result Std.U8))
  := do
  let i ← checked args
  ok (i, state)

/-- [function_item_lifetimes::{impl core::ops::function::FnOnce<(&'_0 u8,), u8> for for<'_0_1> function_item_lifetimes::checked<'_0_1>}::call_once]:
    Source: 'tests/src/function_item_lifetimes.rs', lines 8:0-10:1 -/
def P.Insts.CoreOpsFunctionFnOnceTupleShared0U8U8.call_once
  (state : Std.U8 → Result Std.U8) (args : Std.U8) : Result Std.U8 := do
  checked args

/-- Trait implementation: [function_item_lifetimes::{impl core::ops::function::FnOnce<(&'_0 u8,), u8> for for<'_0_1> function_item_lifetimes::checked<'_0_1>}]
    Source: 'tests/src/function_item_lifetimes.rs', lines 8:0-10:1 -/
@[reducible]
def P.Insts.CoreOpsFunctionFnOnceTupleShared0U8U8 : core.ops.function.FnOnce
  (Std.U8 → Result Std.U8) Std.U8 Std.U8 := {
  call_once := P.Insts.CoreOpsFunctionFnOnceTupleShared0U8U8.call_once
}

/-- Trait implementation: [function_item_lifetimes::{impl core::ops::function::FnMut<(&'_0 u8,), u8> for for<'_0_1> function_item_lifetimes::checked<'_0_1>}]
    Source: 'tests/src/function_item_lifetimes.rs', lines 8:0-10:1 -/
@[reducible]
def P.Insts.CoreOpsFunctionFnMutTupleShared0U8U8 : core.ops.function.FnMut
  (Std.U8 → Result Std.U8) Std.U8 Std.U8 := {
  FnOnceInst := P.Insts.CoreOpsFunctionFnOnceTupleShared0U8U8
  call_mut := P.Insts.CoreOpsFunctionFnMutTupleShared0U8U8.call_mut
}

/-- [function_item_lifetimes::through_function_item]:
    Source: 'tests/src/function_item_lifetimes.rs', lines 11:0-13:1
    Visibility: public -/
def through_function_item (x : Std.U8) : Result Std.U8 := do
  apply P.Insts.CoreOpsFunctionFnMutTupleShared0U8U8 (checked) x

end function_item_lifetimes
