-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [option_operations]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace option_operations

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [option_operations::map]:
    Source: 'tests/src/option_operations.rs', lines 5:0-7:1
    Visibility: public -/
def map
  {T : Type} {U : Type} {F : Type} (coreopsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) (x : Option T) (f : F) :
  Result (Option U)
  := do
  core.option.Option.map coreopsfunctionFnOnceFTupleTUInst x f

/-- [option_operations::map_or]:
    Source: 'tests/src/option_operations.rs', lines 8:0-10:1
    Visibility: public -/
def map_or
  {T : Type} {U : Type} {F : Type} (coreopsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) (x : Option T) (default : U) (f : F) :
  Result U
  := do
  core.option.Option.map_or coreopsfunctionFnOnceFTupleTUInst x default f

/-- [option_operations::cloned]:
    Source: 'tests/src/option_operations.rs', lines 11:0-13:1
    Visibility: public -/
def cloned
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (x : Option T) :
  Result (Option T)
  := do
  core.option.Option.cloned corecloneCloneInst x

/-- [option_operations::phantom]:
    Source: 'tests/src/option_operations.rs', lines 14:0-16:1
    Visibility: public -/
def phantom (T : Type) : Result (core.marker.PhantomData T) := do
  core.marker.phantomDataDefault T

/-- [option_operations::check_map_branches::{closure#3}]
    Source: 'tests/src/option_operations.rs', lines 24:32-24:41 -/
@[reducible]
def check_map_branches.closure_3 := Unit

/-- [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(i32,), i32> for option_operations::check_map_branches::{closure#3}}::call_once]:
    Source: 'tests/src/option_operations.rs', lines 24:32-24:41 -/
def
  check_map_branches.closure_3.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
  (c : check_map_branches.closure_3) (tupled_args : Std.I32) :
  Result Std.I32
  := do
  tupled_args / 2#i32

/-- Trait implementation: [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(i32,), i32> for option_operations::check_map_branches::{closure#3}}]
    Source: 'tests/src/option_operations.rs', lines 24:32-24:41 -/
@[reducible]
def check_map_branches.closure_3.Insts.CoreOpsFunctionFnOnceTupleI32I32 :
  core.ops.function.FnOnce check_map_branches.closure_3 Std.I32 Std.I32 := {
  call_once :=
    check_map_branches.closure_3.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
}

/-- [option_operations::check_map_branches::{closure#2}]
    Source: 'tests/src/option_operations.rs', lines 23:25-23:44 -/
@[reducible]
def check_map_branches.closure_2 := Std.I32

/-- [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(i32,), i32> for option_operations::check_map_branches::{closure#2}}::call_once]:
    Source: 'tests/src/option_operations.rs', lines 23:25-23:44 -/
def
  check_map_branches.closure_2.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
  (c : check_map_branches.closure_2) (tupled_args : Std.I32) :
  Result Std.I32
  := do
  tupled_args + c

/-- Trait implementation: [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(i32,), i32> for option_operations::check_map_branches::{closure#2}}]
    Source: 'tests/src/option_operations.rs', lines 23:25-23:44 -/
@[reducible]
def check_map_branches.closure_2.Insts.CoreOpsFunctionFnOnceTupleI32I32 :
  core.ops.function.FnOnce check_map_branches.closure_2 Std.I32 Std.I32 := {
  call_once :=
    check_map_branches.closure_2.Insts.CoreOpsFunctionFnOnceTupleI32I32.call_once
}

/-- [option_operations::check_map_branches::{closure#1}]
    Source: 'tests/src/option_operations.rs', lines 21:29-21:43 -/
@[reducible]
def check_map_branches.closure_1 := Unit

/-- [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(u32,), u32> for option_operations::check_map_branches::{closure#1}}::call_once]:
    Source: 'tests/src/option_operations.rs', lines 21:29-21:43 -/
def
  check_map_branches.closure_1.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
  (c : check_map_branches.closure_1) (tupled_args : Std.U32) :
  Result Std.U32
  := do
  7#u32 / tupled_args

/-- Trait implementation: [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(u32,), u32> for option_operations::check_map_branches::{closure#1}}]
    Source: 'tests/src/option_operations.rs', lines 21:29-21:43 -/
@[reducible]
def check_map_branches.closure_1.Insts.CoreOpsFunctionFnOnceTupleU32U32 :
  core.ops.function.FnOnce check_map_branches.closure_1 Std.U32 Std.U32 := {
  call_once :=
    check_map_branches.closure_1.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
}

/-- [option_operations::check_map_branches::{closure}]
    Source: 'tests/src/option_operations.rs', lines 20:22-20:36 -/
@[reducible]
def check_map_branches.closure := Unit

/-- [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(u32,), u32> for option_operations::check_map_branches::{closure}}::call_once]:
    Source: 'tests/src/option_operations.rs', lines 20:22-20:36 -/
def check_map_branches.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
  (c : check_map_branches.closure) (tupled_args : Std.U32) :
  Result Std.U32
  := do
  7#u32 / tupled_args

/-- Trait implementation: [option_operations::check_map_branches::{impl core::ops::function::FnOnce<(u32,), u32> for option_operations::check_map_branches::{closure}}]
    Source: 'tests/src/option_operations.rs', lines 20:22-20:36 -/
@[reducible]
def check_map_branches.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32 :
  core.ops.function.FnOnce check_map_branches.closure Std.U32 Std.U32 := {
  call_once :=
    check_map_branches.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32.call_once
}

/-- [option_operations::check_map_branches]:
    Source: 'tests/src/option_operations.rs', lines 19:0-25:1
    Visibility: public -/
def check_map_branches : Result Unit := do
  let o ←
    map check_map_branches.closure.Insts.CoreOpsFunctionFnOnceTupleU32U32 none
      ()
  let b := core.option.Option.is_none o
  massert b
  let i ←
    map_or check_map_branches.closure_1.Insts.CoreOpsFunctionFnOnceTupleU32U32
      none 17#u32 ()
  massert (i = 17#u32)
  let o1 ←
    map check_map_branches.closure_2.Insts.CoreOpsFunctionFnOnceTupleI32I32
      (some 3#i32) 10#i32
  let i1 ← core.option.Option.unwrap o1
  massert (i1 = 13#i32)
  let i2 ←
    map_or check_map_branches.closure_3.Insts.CoreOpsFunctionFnOnceTupleI32I32
      (some 7#i32) 99#i32 ()
  massert (i2 = 3#i32)

/- Unit test for [option_operations::check_map_branches] -/
#assert (check_map_branches).reducesTo ()

/-- [option_operations::CloneProbe]
    Source: 'tests/src/option_operations.rs', lines 27:0-29:1
    Visibility: public -/
structure CloneProbe where
  value : Std.U32

/-- [option_operations::{impl core::clone::Clone for option_operations::CloneProbe}::clone]:
    Source: 'tests/src/option_operations.rs', lines 31:4-35:5
    Visibility: public -/
def CloneProbe.Insts.CoreCloneClone.clone
  (self : CloneProbe) : Result CloneProbe := do
  let i ← self.value + 1#u32
  ok { value := i }

/-- Trait implementation: [option_operations::{impl core::clone::Clone for option_operations::CloneProbe}]
    Source: 'tests/src/option_operations.rs', lines 30:0-36:1 -/
@[reducible]
def CloneProbe.Insts.CoreCloneClone : core.clone.Clone CloneProbe := {
  clone := CloneProbe.Insts.CoreCloneClone.clone
}

/-- [option_operations::check_clone_callback]:
    Source: 'tests/src/option_operations.rs', lines 39:0-43:1
    Visibility: public -/
def check_clone_callback : Result Unit := do
  let o ← cloned CloneProbe.Insts.CoreCloneClone none
  let b := core.option.Option.is_none o
  massert b
  let o1 ← cloned CloneProbe.Insts.CoreCloneClone (some { value := 7#u32 })
  let cp ← core.option.Option.unwrap o1
  massert (cp.value = 8#u32)

/- Unit test for [option_operations::check_clone_callback] -/
#assert (check_clone_callback).reducesTo ()

end option_operations
