-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [scalar_trait_ops]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace scalar_trait_ops

/-- [scalar_trait_ops::add]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 5:0-7:1
    Visibility: public -/
def add (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  U32.traitAdd x y

/-- [scalar_trait_ops::sub]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 8:0-10:1
    Visibility: public -/
def sub (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  U32.traitSub x y

/-- [scalar_trait_ops::rem]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 11:0-13:1
    Visibility: public -/
def rem (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  U32.traitRem x y

/-- [scalar_trait_ops::not]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 14:0-16:1
    Visibility: public -/
def not (x : Std.U32) : Result Std.U32 := do
  U32.traitNot x

/-- [scalar_trait_ops::and]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 17:0-19:1
    Visibility: public -/
def and (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  U32.traitAnd x y

/-- [scalar_trait_ops::or]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 20:0-22:1
    Visibility: public -/
def or (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  U32.traitOr x y

/-- [scalar_trait_ops::xor]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 23:0-25:1
    Visibility: public -/
def xor (x : Std.U32) (y : Std.U32) : Result Std.U32 := do
  U32.traitXor x y

/-- [scalar_trait_ops::shl]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 26:0-28:1
    Visibility: public -/
def shl (x : Std.U32) (n : Std.Usize) : Result Std.U32 := do
  U32.traitShl x n

/-- [scalar_trait_ops::shr]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 29:0-31:1
    Visibility: public -/
def shr (x : Std.U32) (n : Std.Usize) : Result Std.U32 := do
  U32.traitShr x n

/-- [scalar_trait_ops::check_arithmetic]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 34:0-40:1
    Visibility: public -/
def check_arithmetic : Result Unit := do
  let i ← add 4294967294#u32 1#u32
  massert (i = 4294967295#u32)
  let i1 ← sub 4294967295#u32 1#u32
  massert (i1 = 4294967294#u32)
  let i2 ← sub 0#u32 0#u32
  massert (i2 = 0#u32)
  let i3 ← rem 4294967295#u32 32#u32
  massert (i3 = 31#u32)
  let i4 ← rem 4294967295#u32 1#u32
  massert (i4 = 0#u32)

/- Unit test for [scalar_trait_ops::check_arithmetic] -/
#assert (check_arithmetic).reducesTo ()

/-- [scalar_trait_ops::check_bits]:
    Source: 'tests/src/scalar_trait_ops.rs', lines 43:0-52:1
    Visibility: public -/
def check_bits : Result Unit := do
  let i ← not 0#u32
  massert (i = 4294967295#u32)
  let i1 ← and 4294967295#u32 2147483649#u32
  massert (i1 = 2147483649#u32)
  let i2 ← or 2147483648#u32 1#u32
  massert (i2 = 2147483649#u32)
  let i3 ← xor 2147483649#u32 2147483648#u32
  massert (i3 = 1#u32)
  let i4 ← shl 1#u32 31#usize
  massert (i4 = 2147483648#u32)
  let i5 ← shl 2147483648#u32 1#usize
  massert (i5 = 0#u32)
  let i6 ← shr 2147483648#u32 31#usize
  massert (i6 = 1#u32)
  let i7 ← shr 4294967295#u32 0#usize
  massert (i7 = 4294967295#u32)

/- Unit test for [scalar_trait_ops::check_bits] -/
#assert (check_bits).reducesTo ()

end scalar_trait_ops
