-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [slice_last]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace slice_last

/-- [slice_last::last]:
    Source: 'tests/src/slice_last.rs', lines 5:0-7:1
    Visibility: public -/
def last {T : Type} (xs : Slice T) : Result (Option T) := do
  core.slice.Slice.last xs

/-- [slice_last::last_or]:
    Source: 'tests/src/slice_last.rs', lines 9:0-14:1
    Visibility: public -/
def last_or (xs : Slice Std.U32) (fallback : Std.U32) : Result Std.U32 := do
  let o ← core.slice.Slice.last xs
  match o with
  | none => ok fallback
  | some x => ok x

/-- [slice_last::check_last]:
    Source: 'tests/src/slice_last.rs', lines 17:0-21:1
    Visibility: public -/
def check_last : Result Unit := do
  let s ← lift (Array.to_slice (Std.Array.empty Std.U32))
  let i ← last_or s 7#u32
  massert (i = 7#u32)
  let s1 ← lift (Array.to_slice (Array.make 1#usize [ 11#u32 ]))
  let i1 ← last_or s1 7#u32
  massert (i1 = 11#u32)
  let s2 ← lift (Array.to_slice (Array.make 3#usize [ 1#u32, 4#u32, 9#u32 ]))
  let i2 ← last_or s2 7#u32
  massert (i2 = 9#u32)

/- Unit test for [slice_last::check_last] -/
#assert (check_last).reducesTo ()

end slice_last
