-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [vec_operations]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace vec_operations

/-- [vec_operations::truncate]:
    Source: 'tests/src/vec_operations.rs', lines 5:0-7:1
    Visibility: public -/
def truncate
  {T : Type} (v : alloc.vec.Vec T) (len : Std.Usize) :
  Result (alloc.vec.Vec T)
  := do
  alloc.vec.Vec.truncate v len

/-- [vec_operations::as_slice]:
    Source: 'tests/src/vec_operations.rs', lines 8:0-10:1
    Visibility: public -/
def as_slice {T : Type} (v : alloc.vec.Vec T) : Result (Slice T) := do
  ok (alloc.vec.Vec.as_slice v)

/-- [vec_operations::remove]:
    Source: 'tests/src/vec_operations.rs', lines 11:0-13:1
    Visibility: public -/
def remove
  {T : Type} (v : alloc.vec.Vec T) (index : Std.Usize) :
  Result (T × (alloc.vec.Vec T))
  := do
  alloc.vec.Vec.remove v index

/-- [vec_operations::pop]:
    Source: 'tests/src/vec_operations.rs', lines 14:0-16:1
    Visibility: public -/
def pop
  {T : Type} (v : alloc.vec.Vec T) :
  Result ((Option T) × (alloc.vec.Vec T))
  := do
  alloc.vec.Vec.pop v

/-- [vec_operations::clear]:
    Source: 'tests/src/vec_operations.rs', lines 17:0-19:1
    Visibility: public -/
def clear {T : Type} (v : alloc.vec.Vec T) : Result (alloc.vec.Vec T) := do
  alloc.vec.Vec.clear v

/-- [vec_operations::is_empty]:
    Source: 'tests/src/vec_operations.rs', lines 20:0-22:1
    Visibility: public -/
def is_empty {T : Type} (v : alloc.vec.Vec T) : Result Bool := do
  ok (alloc.vec.Vec.is_empty v)

/-- [vec_operations::retain]:
    Source: 'tests/src/vec_operations.rs', lines 23:0-25:1
    Visibility: public -/
def retain
  {T : Type} {F : Type} (coreopsfunctionFnMutFTupleShared0TBoolInst :
  core.ops.function.FnMut F T Bool) (v : alloc.vec.Vec T) (pred : F) :
  Result (alloc.vec.Vec T)
  := do
  alloc.vec.Vec.retain coreopsfunctionFnMutFTupleShared0TBoolInst v pred

/-- [vec_operations::dedup]:
    Source: 'tests/src/vec_operations.rs', lines 26:0-28:1
    Visibility: public -/
def dedup
  {T : Type} (corecmpPartialEqInst : core.cmp.PartialEq T T)
  (v : alloc.vec.Vec T) :
  Result (alloc.vec.Vec T)
  := do
  alloc.vec.Vec.dedup corecmpPartialEqInst v

/-- [vec_operations::check_endpoints]:
    Source: 'tests/src/vec_operations.rs', lines 31:0-45:1
    Visibility: public -/
def check_endpoints : Result Unit := do
  let b ← is_empty (alloc.vec.Vec.new Std.U32)
  massert b
  let (o, v) ← pop (alloc.vec.Vec.new Std.U32)
  let b1 := core.option.Option.is_none o
  massert b1
  let v1 ← alloc.vec.Vec.push v 10#u32
  let v2 ← alloc.vec.Vec.push v1 20#u32
  let v3 ← alloc.vec.Vec.push v2 30#u32
  let (i, v4) ← remove v3 1#usize
  massert (i = 20#u32)
  let s ← as_slice v4
  let i1 := Slice.len s
  massert (i1 = 2#usize)
  let i2 ← Slice.index_usize s 0#usize
  massert (i2 = 10#u32)
  let i3 ← Slice.index_usize s 1#usize
  massert (i3 = 30#u32)
  let (o1, v5) ← pop v4
  let i4 ← core.option.Option.unwrap o1
  massert (i4 = 30#u32)
  let (i5, v6) ← remove v5 0#usize
  massert (i5 = 10#u32)
  let b2 ← is_empty v6
  massert b2

/- Unit test for [vec_operations::check_endpoints] -/
#assert (check_endpoints).reducesTo ()

/-- [vec_operations::check_truncate_and_clear]:
    Source: 'tests/src/vec_operations.rs', lines 48:0-63:1
    Visibility: public -/
def check_truncate_and_clear : Result Unit := do
  let v ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U32) 10#u32
  let v1 ← alloc.vec.Vec.push v 20#u32
  let v2 ← alloc.vec.Vec.push v1 30#u32
  let v3 ← truncate v2 5#usize
  let i := alloc.vec.Vec.len v3
  massert (i = 3#usize)
  let v4 ← truncate v3 1#usize
  let i1 := alloc.vec.Vec.len v4
  massert (i1 = 1#usize)
  let i2 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v4
      0#usize
  massert (i2 = 10#u32)
  let v5 ← clear v4
  let b ← is_empty v5
  massert b
  let v6 ← clear v5
  let v7 ← truncate v6 0#usize
  let b1 ← is_empty v7
  massert b1

/- Unit test for [vec_operations::check_truncate_and_clear] -/
#assert (check_truncate_and_clear).reducesTo ()

/-- [vec_operations::check_retain_state::{closure}]
    Source: 'tests/src/vec_operations.rs', lines 73:19-76:5 -/
@[reducible]
def check_retain_state.closure := Bool

/-- [vec_operations::check_retain_state::{impl core::ops::function::FnMut<(&'_0 u32,), bool> for vec_operations::check_retain_state::{closure}}::call_mut]:
    Source: 'tests/src/vec_operations.rs', lines 73:19-76:5 -/
def
  check_retain_state.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool.call_mut
  (c : check_retain_state.closure) (tupled_args : Std.U32) :
  Result (Bool × check_retain_state.closure)
  := do
  ok (¬ c, ¬ c)

/-- [vec_operations::check_retain_state::{impl core::ops::function::FnOnce<(&'_0 u32,), bool> for vec_operations::check_retain_state::{closure}}::call_once]:
    Source: 'tests/src/vec_operations.rs', lines 73:19-76:5 -/
def
  check_retain_state.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool.call_once
  (c : check_retain_state.closure) (i : Std.U32) : Result Bool := do
  let (b, _) ←
    check_retain_state.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool.call_mut
      c i
  ok b

/-- Trait implementation: [vec_operations::check_retain_state::{impl core::ops::function::FnOnce<(&'_0 u32,), bool> for vec_operations::check_retain_state::{closure}}]
    Source: 'tests/src/vec_operations.rs', lines 73:19-76:5 -/
@[reducible]
def check_retain_state.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool :
  core.ops.function.FnOnce check_retain_state.closure Std.U32 Bool := {
  call_once :=
    check_retain_state.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool.call_once
}

/-- Trait implementation: [vec_operations::check_retain_state::{impl core::ops::function::FnMut<(&'_0 u32,), bool> for vec_operations::check_retain_state::{closure}}]
    Source: 'tests/src/vec_operations.rs', lines 73:19-76:5 -/
@[reducible]
def check_retain_state.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool :
  core.ops.function.FnMut check_retain_state.closure Std.U32 Bool := {
  FnOnceInst :=
    check_retain_state.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U32Bool
  call_mut :=
    check_retain_state.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool.call_mut
}

/-- [vec_operations::check_retain_state]:
    Source: 'tests/src/vec_operations.rs', lines 66:0-80:1
    Visibility: public -/
def check_retain_state : Result Unit := do
  let v ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U32) 10#u32
  let v1 ← alloc.vec.Vec.push v 20#u32
  let v2 ← alloc.vec.Vec.push v1 30#u32
  let v3 ← alloc.vec.Vec.push v2 40#u32
  let v4 ←
    retain
      check_retain_state.closure.Insts.CoreOpsFunctionFnMutTupleShared0U32Bool
      v3 false
  let i := alloc.vec.Vec.len v4
  massert (i = 2#usize)
  let i1 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v4
      0#usize
  massert (i1 = 10#u32)
  let i2 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v4
      1#usize
  massert (i2 = 30#u32)

/- Unit test for [vec_operations::check_retain_state] -/
#assert (check_retain_state).reducesTo ()

/-- [vec_operations::DirectionalEq]
    Source: 'tests/src/vec_operations.rs', lines 83:0-85:1
    Visibility: public -/
structure DirectionalEq where
  key : Std.U32

/-- [vec_operations::{impl core::cmp::PartialEq<vec_operations::DirectionalEq> for vec_operations::DirectionalEq}::eq]:
    Source: 'tests/src/vec_operations.rs', lines 88:4-90:5
    Visibility: public -/
def DirectionalEq.Insts.CoreCmpPartialEqDirectionalEq.eq
  (self : DirectionalEq) (other : DirectionalEq) : Result Bool := do
  if self.key = other.key
  then ok true
  else if self.key = 2#u32
       then ok (other.key = 1#u32)
       else ok false

/-- Trait implementation: [vec_operations::{impl core::cmp::PartialEq<vec_operations::DirectionalEq> for vec_operations::DirectionalEq}]
    Source: 'tests/src/vec_operations.rs', lines 87:0-91:1 -/
@[reducible]
def DirectionalEq.Insts.CoreCmpPartialEqDirectionalEq : core.cmp.PartialEq
  DirectionalEq DirectionalEq := {
  eq := DirectionalEq.Insts.CoreCmpPartialEqDirectionalEq.eq
}

/-- [vec_operations::check_dedup_comparison_direction]:
    Source: 'tests/src/vec_operations.rs', lines 94:0-107:1
    Visibility: public -/
def check_dedup_comparison_direction : Result Unit := do
  let v ←
    alloc.vec.Vec.push (alloc.vec.Vec.new DirectionalEq) ({ key := 1#u32 } :
      DirectionalEq)
  let v1 ← alloc.vec.Vec.push v ({ key := 2#u32 } : DirectionalEq)
  let v2 ← alloc.vec.Vec.push v1 ({ key := 3#u32 } : DirectionalEq)
  let v3 ← alloc.vec.Vec.push v2 ({ key := 2#u32 } : DirectionalEq)
  let v4 ← alloc.vec.Vec.push v3 ({ key := 1#u32 } : DirectionalEq)
  let v5 ← dedup DirectionalEq.Insts.CoreCmpPartialEqDirectionalEq v4
  let i := alloc.vec.Vec.len v5
  massert (i = 4#usize)
  let de ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice DirectionalEq)
      v5 0#usize
  massert (de.key = 1#u32)
  let de1 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice DirectionalEq)
      v5 1#usize
  massert (de1.key = 3#u32)
  let de2 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice DirectionalEq)
      v5 2#usize
  massert (de2.key = 2#u32)
  let de3 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice DirectionalEq)
      v5 3#usize
  massert (de3.key = 1#u32)

/- Unit test for [vec_operations::check_dedup_comparison_direction] -/
#assert (check_dedup_comparison_direction).reducesTo ()

/-- [vec_operations::check_dedup_adjacent_only]:
    Source: 'tests/src/vec_operations.rs', lines 110:0-122:1
    Visibility: public -/
def check_dedup_adjacent_only : Result Unit := do
  let v ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U32) 1#u32
  let v1 ← alloc.vec.Vec.push v 1#u32
  let v2 ← alloc.vec.Vec.push v1 2#u32
  let v3 ← alloc.vec.Vec.push v2 2#u32
  let v4 ← alloc.vec.Vec.push v3 1#u32
  let v5 ← dedup core.cmp.PartialEqU32 v4
  let i := alloc.vec.Vec.len v5
  massert (i = 3#usize)
  let i1 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v5
      0#usize
  massert (i1 = 1#u32)
  let i2 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v5
      1#usize
  massert (i2 = 2#u32)
  let i3 ←
    alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U32) v5
      2#usize
  massert (i3 = 1#u32)

/- Unit test for [vec_operations::check_dedup_adjacent_only] -/
#assert (check_dedup_adjacent_only).reducesTo ()

end vec_operations
